### ISSUE TITLE
SSR error

### ISSUE THREAD

**Issue by qm3ster** [lian-yue/vue-upload-component#87]
doing `import VUpload from 'vue-upload-component/src/FileUpload.vue'` renders fine on client and server.

doing `import VUpload from 'vue-upload-component/src'` as described in SSR instructions gives the following error:
```
  nuxt:render Rendering url /upload +3m
[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token <
[vue-router] uncaught error during route navigation:
./node_modules/vue-upload-component/src/FileUpload.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^
SyntaxError: Unexpected token <
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mihail/Documents/Development/legitus-vuetify-nuxt/node_modules/vue-upload-component/src/index.js:1:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
```
please provide a working SSR setup example.

Additionally, I don't know if this even ties into SSR, what was the section about `webpack-node-externals` for? What does it enable us to do?

**Comment by lian-yue** [comment]
Update the document
https://github.com/lian-yue/vue-upload-component/blob/2.0/docs/en/README.md#ssr-server-isomorphism

--- 

https://github.com/liady/webpack-node-externals

* [**Official `vue-hackernews` demo**](https://github.com/lian-yue/vue-hackernews-2.0/)  

* [**View changes**](https://github.com/lian-yue/vue-hackernews-2.0/commit/bd6c58a30cc6b8ba6c0148e737b3ce9336b99cf8)

**Comment by qm3ster** [comment]
Thank you, I understand what is happening now.
Would you consider releasing your components on npm pre-babelized?
Such as in this template: https://github.com/Akryum/vue-share-components
